# Generated by Django 3.2.2 on 2021-05-13 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Igreja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativa', models.BooleanField(default=True)),
                ('cep', models.IntegerField()),
                ('cidade', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('rua', models.CharField(max_length=200)),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativa', models.BooleanField(default=True)),
                ('cep', models.IntegerField()),
                ('cidade', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('rua', models.CharField(max_length=200)),
                ('nome', models.CharField(max_length=200)),
                ('data_nascimento', models.DateField()),
                ('status', models.IntegerField(choices=[(1, 'MEMBRO'), (3, 'DISCIPLINADO'), (4, 'DESVIADO')])),
                ('departamento', models.IntegerField(choices=[(0, 'MEMBRO'), (1, 'CRIANÇA'), (2, 'ADOLESCENTE'), (3, 'JOVEM'), (4, 'SENHORA'), (5, 'MINISTÉRIO')])),
                ('telefone', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
